version: '3'

services:
  seed:
    image: mycurry/seed:seed

  photocarousel:
    build: .
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    image: mycurry/mongo:cavemongodb